from typing import List, Optional, Dict
from pydantic import BaseModel, Field

# ==========================================
# 1. Question Answering (Q&A) Schemas
# ==========================================
class QARequest(BaseModel):
    question: str = Field(..., description="The educational or general question to answer.")
    model: str = Field("gemini", description="The model to use: 'gemini' or 'lamini'.")

class QAResponse(BaseModel):
    answer: str = Field(..., description="The detailed answer generated by the model.")
    model_used: str = Field(..., description="The name of the model that handled the query.")
    success: bool = Field(True, description="Whether the request succeeded.")
    error: Optional[str] = Field(None, description="Error message if success is False.")

# ==========================================
# 2. Concept Explanation Schemas
# ==========================================
class ExplainRequest(BaseModel):
    concept: str = Field(..., description="The educational topic or concept to explain (e.g., 'Photosynthesis').")
    level: str = Field("intermediate", description="Target learning level: 'beginner', 'intermediate', or 'advanced'.")

class KeyTerm(BaseModel):
    term: str = Field(..., description="The name of the key technical term.")
    definition: str = Field(..., description="A simple, clear definition of the term.")

class ExplainResponse(BaseModel):
    concept: str = Field(..., description="The concept explained.")
    level: str = Field(..., description="The target educational level of explanation.")
    explanation: str = Field(..., description="The core explanation of the concept, structured appropriately for the target level.")
    analogy: str = Field(..., description="A memorable analogy to help visualize the concept.")
    key_terms: List[KeyTerm] = Field(default_factory=list, description="Glossary of key terminology related to this concept.")
    success: bool = Field(True, description="Whether the request succeeded.")
    error: Optional[str] = Field(None, description="Error message if success is False.")

# ==========================================
# 3. Quiz Generation Schemas
# ==========================================
class QuizRequest(BaseModel):
    topic: str = Field(..., description="The topic to generate a quiz on.")
    num_questions: int = Field(5, description="Number of questions to generate (typically 3 to 10).")

class QuizQuestion(BaseModel):
    question_text: str = Field(..., description="The text of the question.")
    options: List[str] = Field(..., description="List of multiple choice options (exactly 4 options recommended).")
    correct_index: int = Field(..., description="0-indexed index of the correct option in the options list.")
    explanation: str = Field(..., description="Detailed explanation of why the correct answer is right and why others are wrong.")

class QuizResponse(BaseModel):
    topic: str = Field(..., description="The topic of the quiz.")
    questions: List[QuizQuestion] = Field(..., description="List of generated quiz questions.")
    success: bool = Field(True, description="Whether the request succeeded.")
    error: Optional[str] = Field(None, description="Error message if success is False.")

# ==========================================
# 4. Text Summarization Schemas
# ==========================================
class SummarizeRequest(BaseModel):
    text: str = Field(..., description="The long educational text or passage to summarize.")

class SummarizeResponse(BaseModel):
    summary: str = Field(..., description="A high-level summary of the text.")
    key_points: List[str] = Field(..., description="Bullet points listing key takeaways.")
    vocabulary: List[KeyTerm] = Field(default_factory=list, description="Difficult words in the text defined for students.")
    success: bool = Field(True, description="Whether the request succeeded.")
    error: Optional[str] = Field(None, description="Error message if success is False.")

# ==========================================
# 5. Learning Recommendation Schemas
# ==========================================
class RecommendRequest(BaseModel):
    goal: str = Field(..., description="The learning goal or career interest (e.g., 'Learn Python for Data Science').")

class RoadmapStep(BaseModel):
    step_number: int = Field(..., description="Sequential step number.")
    title: str = Field(..., description="Title of this learning step.")
    description: str = Field(..., description="Details of what to learn and master in this step.")
    estimated_duration: str = Field(..., description="Suggested duration to complete this step (e.g., 'Week 1-2', '4 hours').")
    resources: List[str] = Field(..., description="A list of suggested free online resources, topics to search, or project ideas.")

class RecommendResponse(BaseModel):
    goal: str = Field(..., description="The user's defined learning goal.")
    overview: str = Field(..., description="A welcoming overview introducing the learning path.")
    roadmap: List[RoadmapStep] = Field(..., description="The step-by-step roadmap.")
    tips: List[str] = Field(..., description="General tips for studying effectively and staying motivated.")
    success: bool = Field(True, description="Whether the request succeeded.")
    error: Optional[str] = Field(None, description="Error message if success is False.")

# ==========================================
# 6. Backend Status Schema
# ==========================================
class HealthStatus(BaseModel):
    status: str
    gemini_configured: bool
    lamini_loaded: bool
    lamini_model_id: str
